# Generated by Django 4.0.4 on 2022-05-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcasting',
            name='status_type',
            field=models.CharField(choices=[(1, 'Reading'), (2, 'Science and Interpretation'), (3, 'Translators')], default='reading', max_length=20),
        ),
    ]
