# Generated by Django 4.0.4 on 2022-05-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0002_alter_broadcasting_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcasting',
            name='status_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('science', 'Science and Interpretation'), ('translators', 'Translators')], default='reading', max_length=20),
        ),
    ]
