# Generated by Django 4.0.4 on 2022-05-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0003_alter_broadcasting_status_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcasting',
            old_name='riwaya_at',
            new_name='riwaya_ar',
        ),
    ]
