# Generated by Django 4.0.4 on 2022-05-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasting', '0005_alter_broadcasting_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcasting',
            name='status_type',
            field=models.CharField(choices=[('1.reading', 'Reading'), ('2.science', 'Science and Interpretation'), ('3.translators', 'Translators')], max_length=20),
        ),
    ]
