# Generated by Django 4.0.4 on 2022-06-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsmaAlHusna',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('transliteration', models.CharField(max_length=250)),
                ('meaning', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
