# Generated by Django 4.0.4 on 2022-05-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmaAlHusna', '0003_remove_asmaalhusna_id_alter_asmaalhusna_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asmaalhusna',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
