# Generated by Django 4.0.4 on 2022-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_component_options_alter_container_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('number',), 'verbose_name_plural': 'Categorios'},
        ),
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
