# Generated by Django 4.0.4 on 2022-07-14 13:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options_category_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
