# Generated by Django 4.0.4 on 2022-05-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('read_surat_link', models.URLField()),
                ('download_surat_link', models.URLField()),
                ('surat_time', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
