# Generated by Django 4.0.4 on 2022-07-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recitations',
            options={'ordering': ('number',)},
        ),
    ]
