# Generated by Django 4.0.4 on 2022-05-17 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='recitations',
            name='reader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quran.reader'),
            preserve_default=False,
        ),
    ]
