# Generated by Django 4.0.4 on 2022-05-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_alter_reader_options_recitations_reader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recitations',
            options={'ordering': ('id',)},
        ),
    ]
